### ISSUE TITLE
Tempo access token

### ISSUE THREAD

**Issue by Thav0** [docta/mercadolibre#2]
Boa tarde!

Quantas horas dura o access token?
Como poderei atualiza-lo ou verificar se foi expirado?

Cumprimentos.

**Comment by lucascono** [comment]
Hello, sorry for the delay, I have not been on github for a long time.

This is a preconfigured PHP League's OAuth 2.0 Client for MercadoLibre, so you will get better and more up-to-date information on their respective websites.

On the wiki there is an example of use and a list of accesses to these websites and repositories.
